-- ─────────────────────────────────────────────────────────────
-- supabase_migration_scholar_portal.sql
--
-- Adds the Scholar Portal on top of the existing staff/admin database.
-- Same Supabase project, same Supabase Auth system — scholars get their
-- own `auth.users` entries (created by staff, see
-- scripts/create-scholar-accounts.mjs) and their own profile table,
-- separate from `public.users` (staff/admin).
--
-- Run this once in the Supabase SQL Editor (Project → SQL Editor → New query).
-- Safe to re-run: every statement uses IF NOT EXISTS / OR REPLACE.
-- ─────────────────────────────────────────────────────────────

-- ── 1. SCHOLARS — core profile ──────────────────────────────
-- `id` mirrors the public.users pattern: it IS the Supabase Auth user id
-- (auth.uid()) for that scholar's login. Staff creates this row together
-- with the Auth account (see scripts/create-scholar-accounts.mjs), so a
-- scholar never self-registers.
create table if not exists public.scholars (
  id                 uuid primary key references auth.users(id) on delete cascade,
  scholar_id_number  text unique not null,
  first_name         text not null,
  last_name          text not null,
  middle_name        text default '',
  -- Birthday isn't in the original field list, but the login screen offers
  -- "name + birthday" as an alternative to "Scholar ID + password", so it
  -- has to live somewhere queryable. Stored here.
  birthday           date not null,
  -- Internal-only, never shown to the scholar or asked for at login: a
  -- synthetic value like "20180000@scholars.cedo.local" generated by
  -- scripts/import-scholars-from-csv.mjs, purely so Supabase Auth (which
  -- requires a unique email per account) has something to key on.
  email              text unique not null,
  contact_no         text default '',
  school             text default '',
  course             text default '',
  civil_status       text default '',
  address            text default '',
  status             text not null default 'active' check (status in ('active','probation','inactive','graduated')),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists idx_scholars_scholar_id_number on public.scholars (scholar_id_number);
create index if not exists idx_scholars_name_birthday on public.scholars (lower(first_name), lower(last_name), birthday);

-- ── 2. SUBJECTS & GRADES — filled in by CEDO staff, linked by scholar_id_number ──
create table if not exists public.scholar_subjects_grades (
  id                 uuid primary key default gen_random_uuid(),
  scholar_id_number  text not null references public.scholars(scholar_id_number) on delete cascade,
  school_year        text not null,          -- e.g. "2025-2026"
  semester           text not null default '', -- e.g. "1st Semester"
  subject            text not null,
  grade              text not null,          -- text, not numeric: schools grade differently (1.00–5.00, letter, INC, etc.)
  remarks            text default '',
  recorded_by        uuid references public.users(id),  -- staff member who entered it
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index if not exists idx_ssg_scholar_id on public.scholar_subjects_grades (scholar_id_number);

-- ── 3. QUEST SCORES — linked by scholar_id_number ───────────
create table if not exists public.scholar_quest_scores (
  id                 uuid primary key default gen_random_uuid(),
  scholar_id_number  text not null references public.scholars(scholar_id_number) on delete cascade,
  quest_name         text not null,
  score              numeric,
  max_score          numeric,
  date_taken         date,
  remarks            text default '',
  recorded_by        uuid references public.users(id),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index if not exists idx_sqs_scholar_id on public.scholar_quest_scores (scholar_id_number);

-- ── 4. SDP — still under development; flexible jsonb payload for now,
--     linked by scholar_id_number, so the shape can evolve without another
--     migration. Tighten this into real columns once SDP is finalized. ──
create table if not exists public.scholar_sdp (
  id                 uuid primary key default gen_random_uuid(),
  scholar_id_number  text not null references public.scholars(scholar_id_number) on delete cascade,
  details            jsonb not null default '{}'::jsonb,
  recorded_by        uuid references public.users(id),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index if not exists idx_sdp_scholar_id on public.scholar_sdp (scholar_id_number);

-- ── 5. SERVICES — future use; same placeholder pattern as SDP ──────
create table if not exists public.scholar_services (
  id                 uuid primary key default gen_random_uuid(),
  scholar_id_number  text not null references public.scholars(scholar_id_number) on delete cascade,
  details            jsonb not null default '{}'::jsonb,
  recorded_by        uuid references public.users(id),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index if not exists idx_services_scholar_id on public.scholar_services (scholar_id_number);

-- ── 6. Helper: is the current auth.uid() a CEDO staff member? ──────
-- Reuses the existing public.users table (staff/division_admin/super_admin).
create or replace function public.is_cedo_staff()
returns boolean
language sql
security definer
stable
as $$
  select exists (select 1 from public.users u where u.id = auth.uid());
$$;

-- ── 7. Row Level Security ───────────────────────────────────
alter table public.scholars enable row level security;
alter table public.scholar_subjects_grades enable row level security;
alter table public.scholar_quest_scores enable row level security;
alter table public.scholar_sdp enable row level security;
alter table public.scholar_services enable row level security;

-- Staff/admin: full read/write on everything (same "shared visibility" model
-- staff already has over each other's records in public.users).
drop policy if exists "staff full access" on public.scholars;
create policy "staff full access" on public.scholars for all
  using (public.is_cedo_staff()) with check (public.is_cedo_staff());

drop policy if exists "staff full access" on public.scholar_subjects_grades;
create policy "staff full access" on public.scholar_subjects_grades for all
  using (public.is_cedo_staff()) with check (public.is_cedo_staff());

drop policy if exists "staff full access" on public.scholar_quest_scores;
create policy "staff full access" on public.scholar_quest_scores for all
  using (public.is_cedo_staff()) with check (public.is_cedo_staff());

drop policy if exists "staff full access" on public.scholar_sdp;
create policy "staff full access" on public.scholar_sdp for all
  using (public.is_cedo_staff()) with check (public.is_cedo_staff());

drop policy if exists "staff full access" on public.scholar_services;
create policy "staff full access" on public.scholar_services for all
  using (public.is_cedo_staff()) with check (public.is_cedo_staff());

-- Scholars: read-only, own records only. (No self-edit yet — staff maintains
-- the record. Add an UPDATE policy scoped to specific columns later if you
-- want scholars to be able to update e.g. their own contact number/address.)
drop policy if exists "scholar reads own profile" on public.scholars;
create policy "scholar reads own profile" on public.scholars for select
  using (id = auth.uid());

drop policy if exists "scholar reads own grades" on public.scholar_subjects_grades;
create policy "scholar reads own grades" on public.scholar_subjects_grades for select
  using (scholar_id_number in (select s.scholar_id_number from public.scholars s where s.id = auth.uid()));

drop policy if exists "scholar reads own quest scores" on public.scholar_quest_scores;
create policy "scholar reads own quest scores" on public.scholar_quest_scores for select
  using (scholar_id_number in (select s.scholar_id_number from public.scholars s where s.id = auth.uid()));

drop policy if exists "scholar reads own sdp" on public.scholar_sdp;
create policy "scholar reads own sdp" on public.scholar_sdp for select
  using (scholar_id_number in (select s.scholar_id_number from public.scholars s where s.id = auth.uid()));

drop policy if exists "scholar reads own services" on public.scholar_services;
create policy "scholar reads own services" on public.scholar_services for select
  using (scholar_id_number in (select s.scholar_id_number from public.scholars s where s.id = auth.uid()));

-- ── 8. Login-lookup RPC ─────────────────────────────────────
-- The Scholar Log In screen lets a scholar identify themselves either by
-- (first name + last name + middle initial + birthday) OR by Scholar ID
-- number, then a single password field. Supabase Auth signs in by EMAIL,
-- not by name or ID — so the app first calls this function to resolve the
-- matching email, then calls supabase.auth.signInWithPassword() with it.
--
-- SECURITY DEFINER + a narrow return (email only) means the public anon key
-- never needs direct SELECT access to the scholars table to do this lookup,
-- and a failed match reveals nothing about which field was wrong.
create or replace function public.resolve_scholar_login_email(
  p_first_name text default null,
  p_last_name text default null,
  p_middle_initial text default null,
  p_birthday date default null,
  p_scholar_id_number text default null
)
returns text
language sql
security definer
stable
as $$
  select email from public.scholars
  where
    (
      p_scholar_id_number is not null
      and scholar_id_number = p_scholar_id_number
    )
    or (
      p_first_name is not null and p_last_name is not null and p_birthday is not null
      and lower(trim(first_name)) = lower(trim(p_first_name))
      and lower(trim(last_name)) = lower(trim(p_last_name))
      and birthday = p_birthday
      and (
        p_middle_initial is null or p_middle_initial = ''
        or lower(left(trim(middle_name), 1)) = lower(left(trim(p_middle_initial), 1))
      )
    )
  limit 1;
$$;

-- Let the public (anon) client call the RPC — it only ever returns an email
-- or null, never any other column, and only on an exact match.
grant execute on function public.resolve_scholar_login_email(text, text, text, date, text) to anon, authenticated;
grant execute on function public.is_cedo_staff() to anon, authenticated;

-- ── 9. Storage bucket note ──────────────────────────────────
-- Reuses the existing "evidence" bucket / storage helpers in src/lib/supabase.ts
-- if scholars ever need to upload files (e.g. requirements). No new bucket
-- required for this phase.
