-- ─────────────────────────────────────────────────────────────
-- supabase_migration_my_surveys_publishing.sql
--
-- Phase 3 of "My Surveys": publishing, the public link, and saving responses.
-- Requires the Phase 1 (core) and Phase 2 (builder) migrations. It only ADDS
-- functions -- it does not redefine any Phase 1/2 function, so the files can be
-- run in any order after those two and re-run safely.
--
-- Public (no-login) access:
--   Respondents are the `anon` role. anon has NO table policy anywhere in the
--   My Surveys tables and never will. The only way in is the two functions
--   below, which are security definer and do all their own checks:
--     get_public_survey(slug)             -> the survey as respondents see it
--     submit_my_survey_response(...)      -> validates and saves one response
--   This is the same "resolve an opaque token, return only whitelisted fields"
--   idiom as get_public_scholar_emergency_info / My Presentations' voting RPCs.
--
--   The public link is /s/<slug>. The slug is 9 random characters from a
--   31-character alphabet (no 0/o/1/i/l): ~44 bits, generated by rejection
--   sampling from gen_random_uuid() bytes so every character is equally likely.
--
-- What submit_my_survey_response() enforces (server-side, per request):
--   survey is Open and not past its closing date; response limit not reached
--   (and the survey closes itself when the limit is hit); one response per
--   device when that setting is on; consent given when consent is required;
--   every answer belongs to this survey and matches its question's type
--   (option ids belong to the question, scale values are in range, dates/times
--   are well-formed, text length is capped); every required question answered.
--   The whole response is saved in one transaction: either all of it or none.
--   Answers to a question version that was replaced while the respondent was
--   filling the form are still accepted (they answered what they were shown).
--
-- Staff functions (owner + editors): get_my_survey_publish_info,
-- save_my_survey_settings, set_my_survey_status. Like save_my_survey they carry
-- the revision the caller last saw and refuse (conflict) if someone else has saved.
-- ─────────────────────────────────────────────────────────────

-- ── Slug generator (internal) ───────────────────────────────

create or replace function public.generate_my_survey_slug()
returns text
language plpgsql
volatile
set search_path = public
as $$
declare
  v_alphabet constant text := '23456789abcdefghjkmnpqrstuvwxyz'; -- 31 characters
  v_slug text := '';
  v_bytes bytea;
  v_i integer;
  v_b integer;
begin
  while char_length(v_slug) < 9 loop
    v_bytes := decode(replace(gen_random_uuid()::text, '-', ''), 'hex');
    for v_i in 0..15 loop
      continue when v_i in (6, 8);   -- these bytes hold the fixed UUID version/variant bits
      v_b := get_byte(v_bytes, v_i);
      continue when v_b >= 248;      -- rejection sampling: 248 = 31 * 8, so every character is equally likely
      v_slug := v_slug || substr(v_alphabet, (v_b % 31) + 1, 1);
      exit when char_length(v_slug) = 9;
    end loop;
  end loop;
  return v_slug;
end;
$$;
revoke execute on function public.generate_my_survey_slug() from public, anon, authenticated;

-- ── Public: read a survey ───────────────────────────────────

create or replace function public.get_public_survey(p_slug text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_s public.my_surveys%rowtype;
  v_items jsonb;
begin
  if p_slug is null or p_slug !~ '^[a-z0-9]{6,32}$' then
    return jsonb_build_object('state', 'not_found');
  end if;

  select * into v_s from public.my_surveys where public_slug = p_slug;
  if not found or v_s.status = 'draft' then
    return jsonb_build_object('state', 'not_found');
  end if;

  -- Close lazily when the closing date has passed or the response limit is reached.
  if v_s.status = 'open' and (
       (v_s.closes_at is not null and v_s.closes_at <= now())
       or (v_s.response_limit is not null
           and (select count(*) from public.my_survey_responses r where r.survey_id = v_s.id) >= v_s.response_limit)
     ) then
    update public.my_surveys set status = 'closed' where id = v_s.id;
    v_s.status := 'closed';
  end if;

  if v_s.status <> 'open' then
    return jsonb_build_object('state', 'closed', 'title', v_s.title);
  end if;

  select coalesce(jsonb_agg(t.item order by t.ord, t.kind_rank), '[]'::jsonb)
  into v_items
  from (
    select s.order_index as ord, 0 as kind_rank,
           jsonb_build_object('kind', 'section', 'id', s.id, 'title', s.title, 'description', s.description) as item
    from public.my_survey_sections s
    where s.survey_id = v_s.id
    union all
    select q.order_index, 1,
           jsonb_build_object(
             'kind', 'question', 'id', q.id, 'questionKey', q.question_key, 'type', q.question_type,
             'text', q.question_text, 'helpText', q.help_text, 'required', q.required,
             'scaleMin', q.scale_min, 'scaleMax', q.scale_max,
             'scaleMinLabel', q.scale_min_label, 'scaleMaxLabel', q.scale_max_label,
             'options', coalesce((
               select jsonb_agg(jsonb_build_object('id', o.id, 'label', o.label) order by o.order_index, o.created_at)
               from public.my_survey_options o where o.question_id = q.id
             ), '[]'::jsonb)
           )
    from public.my_survey_questions q
    where q.survey_id = v_s.id and q.archived_at is null
  ) t;

  return jsonb_build_object(
    'state', 'open',
    'title', v_s.title,
    'description', v_s.description,
    'consentEnabled', v_s.consent_enabled,
    'consentText', v_s.consent_text,
    'thankYouMessage', v_s.thank_you_message,
    'oneResponsePerDevice', v_s.one_response_per_device,
    'items', v_items
  );
end;
$$;
revoke execute on function public.get_public_survey(text) from public;
grant execute on function public.get_public_survey(text) to anon, authenticated;

-- ── Public: submit a response ───────────────────────────────

create or replace function public.submit_my_survey_response(
  p_slug text,
  p_device_id text,
  p_consent boolean,
  p_answers jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_s public.my_surveys%rowtype;
  v_device text;
  v_count integer;
  v_resp uuid;
  v_ans jsonb;
  v_q public.my_survey_questions%rowtype;
  v_seen_keys uuid[] := '{}';
  v_text text;
  v_num numeric;
  v_ids jsonb;
  v_oid uuid;
  v_oids uuid[];
  v_req record;
begin
  if p_slug is null or p_slug !~ '^[a-z0-9]{6,32}$' then
    return jsonb_build_object('ok', false, 'error', 'not_found');
  end if;

  -- Lock the survey row so the response limit and one-per-device rule hold under concurrent submissions.
  select * into v_s from public.my_surveys where public_slug = p_slug for update;
  if not found or v_s.status = 'draft' then
    return jsonb_build_object('ok', false, 'error', 'not_found');
  end if;

  if v_s.status <> 'open' or (v_s.closes_at is not null and v_s.closes_at <= now()) then
    if v_s.status = 'open' then update public.my_surveys set status = 'closed' where id = v_s.id; end if;
    return jsonb_build_object('ok', false, 'error', 'closed');
  end if;

  select count(*) into v_count from public.my_survey_responses where survey_id = v_s.id;
  if v_s.response_limit is not null and v_count >= v_s.response_limit then
    update public.my_surveys set status = 'closed' where id = v_s.id;
    return jsonb_build_object('ok', false, 'error', 'closed');
  end if;

  v_device := nullif(left(coalesce(p_device_id, ''), 100), '');
  if v_s.one_response_per_device then
    if v_device is null then
      return jsonb_build_object('ok', false, 'error', 'invalid', 'message', 'Your browser did not provide a device id. Please reload the page and try again.');
    end if;
    if exists (select 1 from public.my_survey_responses where survey_id = v_s.id and device_id = v_device) then
      return jsonb_build_object('ok', false, 'error', 'duplicate');
    end if;
  end if;

  begin
    if v_s.consent_enabled and coalesce(p_consent, false) is not true then
      raise exception 'MYSURVEY:Please agree to the data privacy statement to submit.';
    end if;
    if p_answers is null or jsonb_typeof(p_answers) <> 'array' or jsonb_array_length(p_answers) > 500 then
      raise exception 'MYSURVEY:Your answers could not be read. Please reload the page and try again.';
    end if;

    insert into public.my_survey_responses (survey_id, device_id, consent_given)
    values (v_s.id, v_device, coalesce(p_consent, false))
    returning id into v_resp;

    for v_ans in select value from jsonb_array_elements(p_answers) loop
      select * into v_q from public.my_survey_questions
      where id = (v_ans ->> 'questionId')::uuid and survey_id = v_s.id;
      if not found then
        raise exception 'MYSURVEY:This survey was changed while you were answering. Please reload the page and try again.';
      end if;
      if v_q.question_key = any (v_seen_keys) then
        raise exception 'MYSURVEY:Your answers could not be read. Please reload the page and try again.';
      end if;
      v_seen_keys := v_seen_keys || v_q.question_key;

      if v_q.question_type in ('short_answer', 'paragraph') then
        v_text := btrim(coalesce(v_ans ->> 'text', ''));
        if char_length(v_text) > 5000 then raise exception 'MYSURVEY:An answer is too long.'; end if;
        if v_text <> '' then
          insert into public.my_survey_answers (response_id, survey_id, question_id, value_text) values (v_resp, v_s.id, v_q.id, v_text);
        end if;

      elsif v_q.question_type = 'date' then
        v_text := btrim(coalesce(v_ans ->> 'text', ''));
        if v_text <> '' then
          if v_text !~ '^\d{4}-\d{2}-\d{2}$' then raise exception 'MYSURVEY:A date answer is not valid.'; end if;
          perform v_text::date; -- raises on impossible dates like 2026-02-31
          insert into public.my_survey_answers (response_id, survey_id, question_id, value_text) values (v_resp, v_s.id, v_q.id, v_text);
        end if;

      elsif v_q.question_type = 'time' then
        v_text := btrim(coalesce(v_ans ->> 'text', ''));
        if v_text <> '' then
          if v_text !~ '^\d{2}:\d{2}(:\d{2})?$' then raise exception 'MYSURVEY:A time answer is not valid.'; end if;
          perform v_text::time;
          insert into public.my_survey_answers (response_id, survey_id, question_id, value_text) values (v_resp, v_s.id, v_q.id, v_text);
        end if;

      elsif v_q.question_type in ('multiple_choice', 'dropdown', 'checkboxes') then
        v_ids := coalesce(v_ans -> 'optionIds', '[]'::jsonb);
        if jsonb_typeof(v_ids) <> 'array' then raise exception 'MYSURVEY:Your answers could not be read. Please reload the page and try again.'; end if;
        if jsonb_array_length(v_ids) > 0 then
          if v_q.question_type <> 'checkboxes' and jsonb_array_length(v_ids) > 1 then
            raise exception 'MYSURVEY:Only one choice is allowed for a question.';
          end if;
          v_oids := '{}';
          for v_oid in select (value #>> '{}')::uuid from jsonb_array_elements(v_ids) loop
            if v_oid = any (v_oids) or not exists (select 1 from public.my_survey_options where id = v_oid and question_id = v_q.id) then
              raise exception 'MYSURVEY:This survey was changed while you were answering. Please reload the page and try again.';
            end if;
            v_oids := v_oids || v_oid;
            insert into public.my_survey_answers (response_id, survey_id, question_id, option_id) values (v_resp, v_s.id, v_q.id, v_oid);
          end loop;
        end if;

      elsif v_q.question_type in ('linear_scale', 'rating') then
        if v_ans ->> 'number' is not null and btrim(v_ans ->> 'number') <> '' then
          v_num := (v_ans ->> 'number')::numeric;
          if v_num <> trunc(v_num) or v_num < coalesce(v_q.scale_min, 1) or v_num > v_q.scale_max then
            raise exception 'MYSURVEY:A scale answer is out of range.';
          end if;
          insert into public.my_survey_answers (response_id, survey_id, question_id, value_number) values (v_resp, v_s.id, v_q.id, v_num);
        end if;
      end if;
    end loop;

    -- Every required question that is current must have an answer (any version of it).
    for v_req in
      select q.question_key, q.question_text from public.my_survey_questions q
      where q.survey_id = v_s.id and q.archived_at is null and q.required
    loop
      if not exists (
        select 1 from public.my_survey_answers a
        join public.my_survey_questions q2 on q2.id = a.question_id
        where a.response_id = v_resp and q2.question_key = v_req.question_key
      ) then
        raise exception 'MYSURVEY:Please answer all required questions before submitting.';
      end if;
    end loop;

    -- Hitting the response limit closes the survey.
    if v_s.response_limit is not null and v_count + 1 >= v_s.response_limit then
      update public.my_surveys set status = 'closed' where id = v_s.id;
    end if;
  exception when others then
    -- The block above is one sub-transaction: the response and its answers are rolled back.
    return jsonb_build_object(
      'ok', false, 'error', 'invalid',
      'message', case when sqlerrm like 'MYSURVEY:%' then substr(sqlerrm, 10)
                      else 'Your answers could not be saved. Please check them and try again.' end
    );
  end;

  return jsonb_build_object('ok', true);
end;
$$;
revoke execute on function public.submit_my_survey_response(text, text, boolean, jsonb) from public;
grant execute on function public.submit_my_survey_response(text, text, boolean, jsonb) to anon, authenticated;

-- ── Staff: publish info ─────────────────────────────────────
-- security INVOKER: RLS decides who can read the survey (any member).

create or replace function public.get_my_survey_publish_info(p_survey_id uuid)
returns jsonb
language plpgsql
stable
set search_path = public
as $$
declare
  v_s public.my_surveys%rowtype;
  v_count integer;
begin
  select * into v_s from public.my_surveys where id = p_survey_id;
  if not found then
    return null;
  end if;
  select count(*) into v_count from public.my_survey_responses where survey_id = p_survey_id;
  return jsonb_build_object(
    'status', v_s.status,
    'publicSlug', v_s.public_slug,
    'publishedAt', v_s.published_at,
    'thankYouMessage', v_s.thank_you_message,
    'oneResponsePerDevice', v_s.one_response_per_device,
    'closesAt', v_s.closes_at,
    'responseLimit', v_s.response_limit,
    'responseCount', v_count,
    'closesAtPassed', v_s.closes_at is not null and v_s.closes_at <= now(),
    'limitReached', v_s.response_limit is not null and v_count >= v_s.response_limit,
    'role', public.my_survey_role(p_survey_id),
    'revision', v_s.revision
  );
end;
$$;
revoke execute on function public.get_my_survey_publish_info(uuid) from public, anon;
grant execute on function public.get_my_survey_publish_info(uuid) to authenticated;

-- ── Staff: settings ─────────────────────────────────────────

create or replace function public.save_my_survey_settings(
  p_survey_id uuid,
  p_expected_revision integer,
  p_settings jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_s public.my_surveys%rowtype;
  v_thanks text;
  v_limit integer;
  v_closes timestamptz;
  v_rev integer;
begin
  v_role := public.my_survey_role(p_survey_id);
  if v_role is null or v_role not in ('owner', 'editor') then
    raise exception 'You do not have permission to change this survey''s settings.';
  end if;

  select * into v_s from public.my_surveys where id = p_survey_id for update;
  if p_expected_revision is distinct from v_s.revision then
    return jsonb_build_object(
      'ok', false, 'conflict', true, 'revision', v_s.revision, 'updatedAt', v_s.updated_at,
      'editedByName', (select nullif(trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, '')), '')
                       from public.users u where u.id = v_s.last_edited_by)
    );
  end if;

  v_thanks := left(btrim(coalesce(p_settings ->> 'thankYouMessage', v_s.thank_you_message)), 2000);
  if v_thanks = '' then v_thanks := 'Thank you for your response!'; end if;

  v_limit := v_s.response_limit;
  if p_settings ? 'responseLimit' then
    v_limit := nullif(p_settings ->> 'responseLimit', '')::integer;
    if v_limit is not null and (v_limit < 1 or v_limit > 1000000) then
      raise exception 'The response limit must be between 1 and 1,000,000.';
    end if;
  end if;

  v_closes := v_s.closes_at;
  if p_settings ? 'closesAt' then
    v_closes := nullif(p_settings ->> 'closesAt', '')::timestamptz;
  end if;

  update public.my_surveys
  set thank_you_message = v_thanks,
      one_response_per_device = coalesce((p_settings ->> 'oneResponsePerDevice')::boolean, one_response_per_device),
      response_limit = v_limit,
      closes_at = v_closes
  where id = p_survey_id
  returning revision into v_rev;

  return jsonb_build_object('ok', true, 'revision', v_rev);
end;
$$;
revoke execute on function public.save_my_survey_settings(uuid, integer, jsonb) from public, anon;
grant execute on function public.save_my_survey_settings(uuid, integer, jsonb) to authenticated;

-- ── Staff: publish / close / reopen ─────────────────────────

create or replace function public.set_my_survey_status(
  p_survey_id uuid,
  p_expected_revision integer,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_s public.my_surveys%rowtype;
  v_problems text[] := '{}';
  v_slug text;
  v_rev integer;
  v_count integer;
  v_q record;
begin
  if p_status not in ('open', 'closed') then
    raise exception 'Unknown status.';
  end if;

  v_role := public.my_survey_role(p_survey_id);
  if v_role is null or v_role not in ('owner', 'editor') then
    raise exception 'You do not have permission to publish or close this survey.';
  end if;

  select * into v_s from public.my_surveys where id = p_survey_id for update;
  if p_expected_revision is distinct from v_s.revision then
    return jsonb_build_object(
      'ok', false, 'conflict', true, 'revision', v_s.revision, 'updatedAt', v_s.updated_at,
      'editedByName', (select nullif(trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, '')), '')
                       from public.users u where u.id = v_s.last_edited_by)
    );
  end if;

  if p_status = 'closed' then
    update public.my_surveys set status = 'closed' where id = p_survey_id and status = 'open'
    returning revision into v_rev;
    return jsonb_build_object('ok', true, 'revision', coalesce(v_rev, v_s.revision), 'publicSlug', v_s.public_slug);
  end if;

  -- Publishing / reopening: the survey must be ready for respondents.
  for v_q in
    select row_number() over (order by q.order_index) as n, q.id, q.question_type, q.question_text,
           (select count(*) from public.my_survey_options o where o.question_id = q.id and btrim(o.label) <> '') as good_options,
           (select count(*) from public.my_survey_options o where o.question_id = q.id and btrim(o.label) = '') as blank_options
    from public.my_survey_questions q
    where q.survey_id = p_survey_id and q.archived_at is null
    order by q.order_index
  loop
    v_count := coalesce(v_count, 0) + 1;
    if btrim(v_q.question_text) = '' then
      v_problems := array_append(v_problems, format('Question %s has no text.', v_q.n));
    end if;
    if v_q.question_type in ('multiple_choice', 'checkboxes', 'dropdown') then
      if v_q.good_options < 2 then
        v_problems := array_append(v_problems, format('Question %s needs at least two options.', v_q.n));
      elsif v_q.blank_options > 0 then
        v_problems := array_append(v_problems, format('Question %s has a blank option.', v_q.n));
      end if;
    end if;
  end loop;
  if coalesce(v_count, 0) = 0 then
    v_problems := array_append(v_problems, 'Add at least one question.');
  end if;
  if v_s.consent_enabled and btrim(v_s.consent_text) = '' then
    v_problems := array_append(v_problems, 'The data privacy consent statement is empty.');
  end if;
  if v_s.closes_at is not null and v_s.closes_at <= now() then
    v_problems := array_append(v_problems, 'The closing date has already passed. Change or clear it in Settings.');
  end if;
  if v_s.response_limit is not null
     and (select count(*) from public.my_survey_responses where survey_id = p_survey_id) >= v_s.response_limit then
    v_problems := array_append(v_problems, 'The response limit has been reached. Raise or clear it in Settings.');
  end if;

  if array_length(v_problems, 1) > 0 then
    return jsonb_build_object('ok', false, 'conflict', false, 'problems', to_jsonb(v_problems));
  end if;

  v_slug := v_s.public_slug;
  if v_slug is null then
    loop
      v_slug := public.generate_my_survey_slug();
      exit when not exists (select 1 from public.my_surveys where public_slug = v_slug);
    end loop;
  end if;

  update public.my_surveys
  set status = 'open', public_slug = v_slug, published_at = coalesce(published_at, now())
  where id = p_survey_id
  returning revision into v_rev;

  return jsonb_build_object('ok', true, 'revision', v_rev, 'publicSlug', v_slug);
end;
$$;
revoke execute on function public.set_my_survey_status(uuid, integer, text) from public, anon;
grant execute on function public.set_my_survey_status(uuid, integer, text) to authenticated;
