import { supabase } from "@/lib/supabase";
import type { EvidenceFile, ProjectStage } from "./researchProjectApi";

const EVIDENCE_BUCKET = "research-project-evidence";

function extensionFor(file: File): string {
  const fromName = file.name.split(".").pop()?.toLowerCase();
  if (fromName && /^[a-z0-9]+$/.test(fromName)) return fromName;
  if (file.type === "application/pdf") return "pdf";
  if (file.type === "application/msword") return "doc";
  if (file.type === "application/vnd.openxmlformats-officedocument.wordprocessingml.document") return "docx";
  if (file.type === "image/png") return "png";
  return "jpg";
}

/** Uploads one evidence file under a project/stage, keyed by a fresh id (crypto.randomUUID(), generated by the caller) so repeatable list rows keep a stable storage path independent of array order. Path: "{projectId}/{stage}/{id}.{ext}" — the leading projectId segment is what the bucket's RLS checks against research_projects.created_by. */
export async function uploadEvidenceFile(
  projectId: string, stage: ProjectStage, id: string, file: File, allowedTypes: string[],
): Promise<{ ok: true; evidence: EvidenceFile } | { ok: false; error: string }> {
  if (!allowedTypes.includes(file.type)) return { ok: false, error: "That file type isn't supported here." };
  const path = `${projectId}/${stage}/${id}.${extensionFor(file)}`;
  const { error } = await supabase.storage.from(EVIDENCE_BUCKET).upload(path, file, { contentType: file.type, upsert: true });
  if (error) return { ok: false, error: error.message };
  return { ok: true, evidence: { id, fileName: file.name, filePath: path, fileType: file.type } };
}

export async function removeEvidenceFile(evidence: EvidenceFile): Promise<{ ok: boolean; error?: string }> {
  const { error } = await supabase.storage.from(EVIDENCE_BUCKET).remove([evidence.filePath]);
  return error ? { ok: false, error: error.message } : { ok: true };
}

/** Short-lived (5 min) signed URL for viewing a private evidence file — used by both the researcher and the evaluator. */
export async function fetchEvidencePreviewUrl(evidence: EvidenceFile): Promise<string | null> {
  const { data, error } = await supabase.storage.from(EVIDENCE_BUCKET).createSignedUrl(evidence.filePath, 300);
  if (error || !data) return null;
  return data.signedUrl;
}
